theme: just-the-docs
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-toc
gem "github-pages", group: :jekyll_plugins

toc:
  min_level: 1
  max_level: 3
  list_class: toc
  list_class: toc__list
  sublist_class: toc__sublist

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: note
    color: yellow

basewebsite: /docs
website: https://lolrobbe2.github.io/lunaDocs/docs

aux_links:
    "Luna engine on Github":
    - "//github.com/lolrobbe2/luna"

    "Luna docs on Github":
    - "//github.com/lolrobbe2/lunaDocs"

aux_links_new_tab: true