theme: just-the-docs
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: note
    color: yellow

basewebsite: /docs
website: https://lolrobbe2.github.io/lunaDocs/docs